### ISSUE TITLE
Got errors when I run yarn for installation.

### ISSUE THREAD

**Issue by bluehenry** [BHP-DevHub/bhp-digital-design-system#1]
C:\Workspace\GitHub\bhp-digital-design-system>yarn
yarn install v0.27.5
info No lockfile found.
[1/4] Resolving packages...
warning gatsby > babel-preset-es2015@6.24.1: �  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
warning There appears to be trouble with your network connection. Retrying...
warning gatsby-plugin-sharp > imagemin-pngquant > pngquant-bin > bin-build > download > gulp-decompress > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guide
lines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
[2/4] Fetching packages...
warning fsevents@1.1.3: The platform "win32" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "bhp-ui-react@0.0.2" has incorrect peer dependency "rc-time-picker@3.2.1".
warning "bhp-ui-react@0.0.2" has incorrect peer dependency "react-autosuggest@9.3.2".
warning "bhp-ui-react@0.0.2" has incorrect peer dependency "react-dates@16.0.1".
warning "bhp-ui-react@0.0.2" has incorrect peer dependency "reactstrap@5.0.0-alpha.4".
warning "bootstrap@4.0.0" has unmet peer dependency "jquery@1.9.1 - 3".
[4/4] Building fresh packages...
[-/5] ⠁ waiting...
[2/5] ⠂ node-sass
[3/5] ⠂ pngquant-bin
[4/5] ⠂ cwebp-bin
error C:\Workspace\GitHub\bhp-digital-design-system\node_modules\sharp: Command failed.
Exit code: 1
Command: C:\WINDOWS\system32\cmd.exe
Arguments: /d /s /c node-gyp rebuild
Directory: C:\Workspace\GitHub\bhp-digital-design-system\node_modules\sharp
Output:
C:\Workspace\GitHub\bhp-digital-design-system\node_modules\sharp>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_mod
ules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.4.0 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\jijuh9\AppData\Local\Programs\Python\Python36-32\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Workspace\GitHub\bhp-digital-design-system\node_modules\sharp
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

![yarn](https://user-images.githubusercontent.com/9276380/36716585-c8a1239c-1bd5-11e8-8fab-7f47580bceb9.png)

**Comment by Leong21** [comment]
Hi @bluehenry, 
I'd encountered the same error as well.
It appears to be a compatibility issue between windows and gyp.

Please refer to [https://www.gatsbyjs.org/docs/gatsby-on-windows/](https://www.gatsbyjs.org/docs/gatsby-on-windows/) and let me know how it goes.
I followed the instructions there but still unable to get it compile under windows.
I ended up compiling the source code under Mac OSX.
